package error

import "fmt"

type ErrorCode string

func (e ErrorCode) ToString() string {
	return fmt.Sprintf("%s", e)
}

const (
	REQUEST_NOT_VALID          ErrorCode = "REQUEST_NOT_VALID"
	SQL_INSERT_ERROR           ErrorCode = "SQL_INSERT_ERROR"
	SQL_UPDATE_ERROR           ErrorCode = "SQL_UPDATE_ERROR"
	SQL_FETCH_ERROR            ErrorCode = "SQL_FETCH_ERROR"
	API_URL_PARSING_ERROR      ErrorCode = "API_URL_PARSING_ERROR"
	API_REQUEST_CREATION_ERROR ErrorCode = "API_REQUEST_CREATION_ERROR"
	API_REQUEST_ERROR          ErrorCode = "API_REQUEST_ERROR"
	API_REQUEST_STATUS_ERROR   ErrorCode = "API_REQUEST_STATUS_ERROR"
	JSON_SERIALIZATION_ERROR   ErrorCode = "JSON_SERIALIZATION_ERROR"
	JSON_DESERIALIZATION_ERROR ErrorCode = "JSON_DESERIALIZATION_ERROR"
	FORM_SERIALIZATION_ERROR   ErrorCode = "FORM_SERIALIZATION_ERROR"
)
